services:
  api:
    build: ./employeemanager
    container_name: employeemanager-api
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: employeemanager
    ports:
      - "8080:8080"
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  frontend:
    build: ./employeemanagerapp
    container_name: employeemanager-frontend
    ports:
      - "4200:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data:
