services:
  db:
    image: mysql:8.4
    container_name: employeemanager-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"     # Workbench on Windows uses 3307
    volumes:
      - employeersapp_db_data:/var/lib/mysql
    networks:
      internal:
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  api:
    build: ./employeemanager
    container_name: employeemanager-api
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      internal:
      shared:
        aliases:
          - api
    restart: unless-stopped

volumes:
  employeersapp_db_data:
    external: true

networks:
  internal:
  shared:
    external: true
    name: employeemanager_shared
